name: GitHub Contribution Snake
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Generate Snake SVG
        uses: platane/snk@v1.0.1
        with:
          username: chetanverma07
          color: "00F7FF"
      - name: Commit SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake"
          git push